name: Build & Start Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: '0 3 1 * *'

jobs:
  build:
    name: Make Build & Start Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies (with cache)
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Clean
        run: npm run clean

      - name: Build
        run: npm run build:prefix-paths
        env:
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}

      - name: Cache ghostscript
        uses: actions/cache@v2
        id: cache-ghostscript
        with:
          path: "~/ghostscript"
          key: ghostscript

      - name: Install ghostscript
        env:
          CACHE_HIT: ${{steps.cache-ghostscript.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/ghostscript/* /
          else
            sudo apt-get install --yes ghostscript
            mkdir -p ~/ghostscript
            sudo dpkg -L ghostscript | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/ghostscript/
          fi

      - name: Build CV PDF
        run: |
          cp -a ${PWD}/src/components/typography/fonts/. ~/.fonts
          fc-cache -f -v
          npm run build:cv-pdf

      - name: Start Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: public
