name: Build & Start Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 1 * *'

jobs:
  build:
    name: Make Build & Start Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:prefix-paths
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}

      - name: Build CV PDF
        run: |
          cp -a ${PWD}/src/assets/fonts/. ~/.fonts
          fc-cache -f -v
          npm run build:cv-pdf

      - name: Start Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: public

