name: Check PR

on: [pull_request]

jobs:
  check-pr:
    name: Run Type Check & Linters

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Check types
        run: npm run type-check

      - name: Check linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v4
